language: rust
cache: cargo
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failure:
        - rust: nightly
    fast_finish: true
    - rust: stable
      script:
          - cargo build --verbose
          - cargo test --verbose
          - cargo fmt -- --write-mode=diff
